/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'sendAckMsg'
 * message type.
 */

public class sendAckMsg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 2;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 137;

    /** Create a new TestSerialMsg of size 2. */
    public sendAckMsg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new TestSerialMsg of the given data_length. */
    public sendAckMsg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new TestSerialMsg with the given data_length
     * and base offset.
     */
    public sendAckMsg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new TestSerialMsg using the given byte array
     * as backing store.
     */
    public sendAckMsg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new TestSerialMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public sendAckMsg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new TestSerialMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public sendAckMsg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new TestSerialMsg embedded in the given message
     * at the given base offset.
     */
    public sendAckMsg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new TestSerialMsg embedded in the given message
     * at the given base offset and length.
     */
    public sendAckMsg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <sendAckMsg> \n";
      try {
        s += "  [sample_value=0x"+Long.toHexString(get_sample_value())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: sample_value
    //   Field type: int, unsigned
    //   Offset (bits): 0
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'sample_value' is signed (false).
     */
    public static boolean isSigned_sample_value() {
        return false;
    }

    /**
     * Return whether the field 'sample_value' is an array (false).
     */
    public static boolean isArray_sample_value() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'sample_value'
     */
    public static int offset_sample_value() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'sample_value'
     */
    public static int offsetBits_sample_value() {
        return 0;
    }

    /**
     * Return the value (as a int) of the field 'sample_value'
     */
    public int get_sample_value() {
        return (int)getUIntBEElement(offsetBits_sample_value(), 16);
    }

    /**
     * Set the value of the field 'sample_value'
     */
    public void set_sample_value(int value) {
        setUIntBEElement(offsetBits_sample_value(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'sample_value'
     */
    public static int size_sample_value() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'sample_value'
     */
    public static int sizeBits_sample_value() {
        return 16;
    }

}
